<?php

/**
 * Author: Cameron Crosby
 * Date: 11/20/2024
 * File: user.class.php
 * Description: Defines the User class. This class is responsible for storing all data about a given user
 */
class User
{
    // Private attributes
    private ?int $id; // auto-generated
    private string $firstName, $lastName, $email, $password, $role;

    // Constructor
    public function __construct($fn, $ln, $email, $password, $role) {
        $this->firstName = $fn;
        $this->lastName = $ln;
        $this->email = $email;
        $this->password = $password;
        $this->role = $role;
    }

    // get the user's autogenerated id
    public function getId(): ?int
    {
        return $this->id;
    }

    // set user's autogenerated id
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    // get user's first name
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    // set user's first name
    public function setFirstName(string $firstName): User
    {
        $this->firstName = $firstName;
        return $this;
    }

    // get user's last name
    public function getLastName(): string
    {
        return $this->lastName;
    }

    // set user's last name
    public function setLastName(string $lastName): User
    {
        $this->lastName = $lastName;
        return $this;
    }

    // get user's email
    public function getEmail(): string
    {
        return $this->email;
    }

    // set user's email
    public function setEmail(string $email): User
    {
        $this->email = $email;
        return $this;
    }

    // get user's password
    public function getPassword(): string
    {
        return $this->password;
    }

    // set user's password
    public function setPassword(string $password): User
    {
        $this->password = $password;
        return $this;
    }

    // get user's role
    public function getRole(): string
    {
        return $this->role;
    }

    // set user's role
    public function setRole(string $role): User
    {
        $this->role = $role;
        return $this;
    }

}