<?php
/**
 * Author: Cameron Crosby
 * Date: 12/4/2024
 * File: transaction.class.php
 * Description: Defines the Transaction class. This stores one record from the transaction table
 */

class Transaction
{
    // private attributes
    private ?int $transactionId; // auto-generated
    private int $accountId;
    private string $type, $timestamp;
    private float $amount;

    // constructor
    public function __construct($accountId, $type, $amount, $timestamp) {
        $this->accountId = $accountId;
        $this->type = $type;
        $this->amount = $amount;
        $this->timestamp = $timestamp;
    }

    // get the transaction's autogenerated id
    public function getId(): ?int {
        return $this->transactionId;
    }

    // set autogenerated id
    public function setId(?int $id): Transaction {
        $this->transactionId = $id;
        return $this;
    }

    // get the transaction's associated account id
    public function getAccountId(): int
    {
        return $this->accountId;
    }

    // set the account id
    public function setAccountId(int $accountId): Transaction
    {
        $this->accountId = $accountId;
        return $this;
    }

    // get the transaction type
    public function getType(): string
    {
        return $this->type;
    }

    // set the transaction type
    public function setType(string $type): Transaction
    {
        $this->type = $type;
        return $this;
    }

    // get the transaction timestamp
    public function getTimestamp(): string
    {
        return $this->timestamp;
    }

    // set the transaction timestamp
    public function setTimestamp(string $timestamp): Transaction
    {
        $this->timestamp = $timestamp;
        return $this;
    }

    // get the transaction amount
    public function getAmount(): float
    {
        return $this->amount;
    }

    // set the transaction amount
    public function setAmount(float $amount): Transaction
    {
        $this->amount = $amount;
        return $this;
    }

}